### ISSUE TITLE
Predicted timer should stop updating if the car stops racing (time keeps counting up up to a high value)

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#106]

**Comment by stieg** [comment]
Why?  Its just doing its job.  How is it supposed to know we are no longer racing?

**Comment by brentpicasso** [comment]
Because it will count up to 100's of minutes if left unchecked; it looks
awkward to the user.

I would say it should stop if it reaches some 10x multiple of the best lap
time.

On Mon, Jan 4, 2016 at 10:34 AM, Andrew Stiegmann <notifications@github.com>
wrote:

> Why? Its just doing its job. How is it supposed to know we are no longer
> racing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autosportlabs/RaceCapture-Pro_firmware/issues/106#issuecomment-168761918>
> .
>



-- 
Brent Picasso
*Autosport Labs <http://www.autosportlabs.com>*
*Technology for Race and Street*

**Comment by ryandoherty** [comment]
I agree, it's a poor user experience. I think stopping at even a 2x of the best time may be ok.

**Comment by stieg** [comment]
Got it.  Need an upper limit on the predicted timer value.
