### ISSUE TITLE
MK2 - Timer channel diagnosis (Timer channel 3, see source code)

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#119]

**Comment by stieg** [comment]
Insufficient description.  Re-open with better description if worthy of fixing.

**Comment by brentpicasso** [comment]
A placeholder issue that refers to this code comment:
https://github.com/autosportlabs/RaceCapture-Pro_firmware/blob/master/stm32_base/hal/timer_stm32/timer_device_stm32.c#L335

**Comment by stieg** [comment]
Timer 3 on MK2 has a hardware bug where we can not calculate duty cycle because the line that is used for the CCR has no extension to the slave controller (we use CCR3, only inputs to CCR 1 and CCR 2 have extensions to slave controller).  Hence there is nothing that can be done here that hasn't already been done as of 2.9.0.  Thus closing.
