### ISSUE TITLE
Channel precision not saved to log file

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#124]
Looks like a channel's precision is not in the meta info in log files. This would be useful to have for loading log files later and for test scripts that send data to RCL.

**Comment by stieg** [comment]
@brentpicasso / @ryandoherty I don't understand how this info would be useful?  Can you elaborate?

**Comment by brentpicasso** [comment]
It would represent the complete Channel configuration in the log file
metadata. Right now this value is missing from metadata, but min/max are
present, for instance.

On Mon, Jan 4, 2016 at 10:31 AM, Andrew Stiegmann <notifications@github.com>
wrote:

> @brentpicasso <https://github.com/brentpicasso> / @ryandoherty
> <https://github.com/ryandoherty> I don't understand how this info would
> be useful? Can you elaborate?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autosportlabs/RaceCapture-Pro_firmware/issues/124#issuecomment-168761147>
> .
>



-- 
Brent Picasso
*Autosport Labs <http://www.autosportlabs.com>*
*Technology for Race and Street*

**Comment by stieg** [comment]
I understand that.  What I'm trying to grasp is why we need this?  Who would use it or find it valuable?

**Comment by brentpicasso** [comment]
It's a hint for downstream systems. Like min/max is sort of a hint.

On Mon, Jan 4, 2016 at 10:49 AM, Andrew Stiegmann <notifications@github.com>
wrote:

> I understand that. What I'm trying to grasp is why we need this? Who would
> use it or find it valuable?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autosportlabs/RaceCapture-Pro_firmware/issues/124#issuecomment-168765931>
> .
>



-- 
Brent Picasso
*Autosport Labs <http://www.autosportlabs.com>*
*Technology for Race and Street*

**Comment by stieg** [comment]
I still don't see the value I'm afraid.  I see the value of min and max because we could use those to specify the low and high points of a gauge.  This would allow us to make full use of a gauge when rendering.  With precision I don't see the same value because its implicit in how the values are given.  If we send a float value that looks something like `1.23`, you can imply that the precision must be at least 2 (it could be higher).

Point here is that I don't feel we should send data that has no direct use.  If there is a direct use, then I'm for it.  Otherwise leave it out as it only would bloat the data stream we send back.

**Comment by stieg** [comment]
closing due to no response.
