### ISSUE TITLE
Have Analogue channels always include raw voltage along with scaled channel values

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#162]
When setting up the unit, it would be very helpful to have a screen that displayed raw voltage for all channels, so that mapped or scaled channels could be checked without switching them all back to voltage.

**Comment by stieg** [comment]
Unfortunately this is really not trivial to do.  Due to the way we interpolate channels in RCP the voltage value is manipulated before its reported in the telemetry stream.

A possible workaround here is to put the same voltage input into two inputs, one which you are trying to calculate setup the scaling on and the other which you simply leave as a voltage value.  Then you can have both.  Closing because we are unlikely to solve this.
