### ISSUE TITLE
Change distance to be calculated by integrating speed over time.

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#178]
Customer feedback: http://www.autosportlabs.org/viewtopic.php?p=22581#22581

**Comment by stieg** [comment]
Will need to test if this is more accurate than what we currently have.

**Comment by ryandoherty** [comment]
I think a user commented in the forums or via email a long time ago with data that showed it was (used RCP log to derive distance based on speed). We still need to test, but seems promising.

**Comment by JJMcDonough** [comment]
I'm not sure what method can be used to verify accuracy, but spot checking one of my files I do see about a 3% difference in distance over 1 mile comparing the raw distance channel (GPS set to 10hz) to my speed integration distance calc. Like I said on the message board, when I was running too high of a GPS sampling rate, the raw distance was way off because the position data jumped around a bunch. Happy to provide file/feedback/testing.

**Comment by brentpicasso** [comment]
Hi, great feedback.  Do you have a sense which one is more accurate? IOW, did you also compare this against a known distance?

**Comment by JJMcDonough** [comment]
Did not compare against a known distance. I have DL1 data on the same course, but it's a bit tricky to identify the finish line from the data.

**Comment by stieg** [comment]
merged with commit 18b423aea03d98f69c4a54f4d0aa341fe51688c7
