### ISSUE TITLE
flash RCP firmware to physically connected RCP, run a basic test

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#213]
to flash: asl_f4_loader -f <firmware.ihex>

minimal basic functionality to test if alive:
1) can you connect to it over /dev/ttyACMxx
2) do you get the command prompt text after sending CRLF

if basic tests fail, fail the build.

**Comment by stieg** [comment]
To complete this we would need some server available in the lab that is hooked up to an RCP that could accept a remote connection and implement this test.  I don't see anyone implementing this so I'm going to close this as won't fix due to lack of interest.  Re-open if you want to write the script and setup the machine to handle this behavior.
