### ISSUE TITLE
Need sleep() command for Lua

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture-Pro_firmware#353]
Need the ability to sleep in Lua Scripting. Add sleep() command to call the FreeRTOS() delay function to enact a sleep effect.

**Comment by stieg** [comment]
Not sure if this is a good idea since it could adversely affect other parts of the script if a user doesn't use it correctly.  Suggest using [getUptime()](https://www.autosportlabs.net/RaceCapturePro_Lua_Scripting#getUptime.28.29) which gives you uptime in ms.  Do some calculations with that instead and delay execution of code until X ms have passed.

**Comment by stieg** [comment]
But if we do decide to go this way, shouldn't be too difficult to do.  Always a bonus really :P.
