### ISSUE TITLE
Reset distance channel to 0 when crossing the start

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#359]
RaceCapture/Live is seeing lap data where a new lap starts, but the Distance channel's value starts at values much greater than 0 (0.2, 0.5, etc). This is most likely due to having separate start/finish points and RCP is 'counting' the distance between finish => start, making the Distance channel start at a high value.

This breaks a lot of functionality in other systems and also makes it impossible to compare lap data over distance.

**Comment by ryandoherty** [comment]
Nominating this to be fixed/investigated for the next firmware release.

**Comment by stieg** [comment]
Interesting.  I'll have a look.

**Comment by ryandoherty** [comment]
Tough part is I saw this for telemetry data from a RC => phone => RCL connection, so no raw logs. Need to get the app recording data locally too.

**Comment by stieg** [comment]
So far investigation has found minor issues in how start logic is handled.  A patch is in progress but not known if it will directly solve this issue.  We must be able to support us starting with a distance value > 0 (but not one that is .5 miles) since the implementation of the launch control feature requires us to start a lap with a non-zero distance (because launch control only knows you have started your lap _after_ it has detected a successful launch).

**Comment by stieg** [comment]
Tested and passed as expected.

**Comment by stieg** [comment]
ok to test

**Comment by stieg** [comment]
test this please

**Comment by stieg** [comment]
Need to port fix to 2.8.7

**Comment by stieg** [comment]
PR: https://github.com/autosportlabs/RaceCapture-Pro_firmware/pull/393
