### ISSUE TITLE
Create USB driver for RaceCapture

### ISSUE THREAD

**Issue by stieg** [autosportlabs/RaceCapture-Pro_firmware#380]
The new RaceCapture unit will need a USB driver written for it so that we can do firmware upgrades.

**Comment by Jeff-Ciesielski** [comment]
I'll take this and bootloader if I can get my hands on some hardware :)

**Comment by brentpicasso** [comment]
Actually, If the firmware driver is with the same driver as RCP, then no new windows driver will need to be written since Windows 10 has a built in ACM driver. For Windows 7 we can use our existing driver; Win 8 we have the signed driver work-around.   

Bootloader issue: https://github.com/autosportlabs/RaceCapture-Pro_firmware/issues/381

**Comment by stieg** [comment]
Email me one your address and I'll send you one of my two prototype units.
