### ISSUE TITLE
Make precision on gyro channels (yaw / pitch / roll ) zero position

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture-Pro_firmware#815]
since we're dealing with hundreds of degrees of rotation / sec, having two decimal points of precision seems excessive. Should represent the value in whole numbers.

**Comment by stieg** [comment]
Probably not a bad idea.  We should lump the fix for this in with #422 so that we can see the high value Gyro readouts that trade off sensitivity.  Also you are not dealing with "100s of degrees of rotation a second".  If they are rotating that fast they are likely spinning or going through a hairpin turn.  Still I agree that the sensitivity is not necessary.  Bumping to 2.11 since this is not necessary for 2.10.  If there is time left over I will re-evaluate.

**Comment by stieg** [comment]
PR #816 fixes this.

**Comment by stieg** [comment]
Merged
