### ISSUE TITLE
Expose current direct CAN mapping value in Lua

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture-Pro_firmware#939]
Similar to readOBD2() in lua, we need a function that exposes the current value for a direct CAN mapping. 

There's no convenient unique ID like we have for readOBD2(), since you can extract multiple values from the same CAN message. 

Some ideas:

* We can do it based on CAN mapping index, but that's pretty fragile and will break the script if the ordering of the CAN mapping changes. 
* We can key it off of the combination of CAN ID / offset / length since those are typically unique, but that would be a bit cumbersome. 
* We can query based on the actual channel name, which would make it work for any channel. This is likely the best option, but it would require an efficient / hashed lookup if requesting by name.

**Comment by zandr** [comment]
My 0.02: I'd suggest the third approach, since there's already pretty good UI to assign CAN mappings to channels, and users will get grumpy if you make them duplicate that effort in Lua. As far as efficiency goes, it wouldn't matter much if the name lookup were expensive if we had a getChannelId("ChannelName"). Then we can use the ID from then on and avoid the lookup.

**Comment by zandr** [comment]
My 0.02: I'd suggest the third approach, since there's already pretty good UI to assign CAN mappings to channels, and users will get grumpy if you make them duplicate that effort in Lua. As far as efficiency goes, it wouldn't matter much if the name lookup were expensive if we had a getChannelId("ChannelName"). Then we can use the ID from then on and avoid the lookup.
